### ISSUE TITLE
Dockerfile-prod not recognized

### ISSUE THREAD

**Issue by zachbugay** [asbjornenge/Docker.tmbundle#31]
I have two docker-files in my repository. A Dockerfile, and a Dockerfile-prod (to denote dev versus production.) The Dockerfile-prod does not have any syntax help or anything.

**Comment by blag** [comment]
If you're using Sublime, the [`.Dockerfile` and `.dockerfile` extensions](https://github.com/asbjornenge/Docker.tmbundle/blob/master/Syntaxes/Dockerfile.sublime-syntax#L5) should both match this syntax. Please rename your production Dockerfile accordingly.

Unfortunately, since there isn't really an official standard for naming different Dockerfiles, I'm not super interested in supporting everybody's naming variances.

**Comment by princemaple** [comment]
Does the first line not guess correctly? You can use https://packagecontrol.io/packages/ApplySyntax to apply extra rules to choose syntax for you automatically.
